version: '3.9'
services:
  app:
    container_name: app-container
    image: node:16
    volumes:
      - type: bind
        source: "./app"
        target: "/app"
    working_dir: "/app"
    ports:
      - "8910:8910"
      - "8911:8911"
      - "5555:5555"
      - "7910:7910"
    tty: true